# action.yml
name: 'BruhAction'
description: 'A test action'
inputs:
  input1:
    description: 'The first input'
    required: true
  input2:
    description: 'The second input'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.input1 }}
    - ${{ inputs.input2 }}
